export const TASKS_TYPES = {
  FETCH_TASKS_START: "FETCH_TASKS_START",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILED: "FETCH_TASKS_FAILED",
  SET_CREATED_AT_DATE: "SET_CREATED_AT_DATE",
};
