export const TASKS_TYPES = {
  FETCH_TASKS_START: "FETCH_TASKS_START",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILED: "FETCH_TASKS_FAILED",
  FETCH_USER_LISTS_START: "FETCH_USER_LISTS_START",
  FETCH_USER_LISTS_SUCCESS: "FETCH_USER_LISTS_SUCSESS",
  FETCH_USER_LISTS_FAILED: "FETCH_USER_LISTS_FAILED",
};
