export const LINEUPS_TYPES = {
  FETCH_LINEUPS_START: "FETCH_LINEUPS_START",
  FETCH_LINEUPS_SUCCESS: "FETCH_LINEUPS_SUCCESS",
  FETCH_LINEUPS_FAILED: "FETCH_LINEUPS_FAILED",
  CREATE_LINEUPS_START: "CREATE_LINEUPS_START",
  DELETE_LINEUPS_START: "DELETE_LINEUPS_START",
};
