export const LIST_TYPES = {
  FETCH_LIST_START: "FETCH_LIST_START",
  FETCH_LIST_SUCCESS: "FETCH_LIST_SUCCESS",
  FETCH_LIST_FAILED: "FETCH_LIST_FAILED",
  CREATE_LIST_START: "CREATE_LIST_START",
  EDIT_LIST_START: "EDIT_LIST_START",
  DELETE_LIST_START: "DELETE_LIST_START",
};
