export const TASK_LIST_TYPES = {
  FETCH_TASKS_START: "FETCH_TASKS_START",
  FETCH_TASKS_BY_LIST_ID_START: "FETCH_TASKS_BY_LIST_ID_START",
  SET_FILTERS: "SET_FILTERS",
  SET_SORTING: "SET_SORTING",
  SET_FILTERED_LIST: "SET_FILTERED_LIST",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILED: "FETCH_TASKS_FAILED",
};
