export const USER_TYPE = {
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "SIGN_IN_FAILED",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SING_UP_START: "SING_UP_START",
  LOG_OUT_START: "LOG_OUT_START",
};
