export const TASK_TYPES = {
  CREATE_TASK_START: "CREATE_TASK_START",
  DELETE_TASK_START: "DELETE_TASK_START",
  EDIT_TASK_START: "EDIT_TASK_START",
  UPDATE_TASK_STATUS_START: "UPDATE_TASK_STATUS_START",
  UPDATE_TASK_PRIORITY_START: "UPDATE_TASK_PRIORITY_START",
  TASK_SUCCESS: "TASK_SUCCESS",
  TASK_FAILED: "TASK_FAILED",
};
